//Auto gen file

var configdb = configdb || {};

configdb.skill = {};

configdb.skill['10101'] = {
	key: 10101.0,
	name: undefined,
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 10.0,
	velocity_ground_x: 180.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 30.0,
	atk_power: 1.0,
	cd: 0.0,
};

configdb.skill['10102'] = {
	key: 10102.0,
	name: undefined,
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 10.0,
	velocity_ground_x: 180.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 50.0,
	atk_power: 1.1,
	cd: 0.0,
};

configdb.skill['10103'] = {
	key: 10103.0,
	name: undefined,
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 8.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 150.0,
	velocity_ground_x: 200.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 200.0,
	velocity_floating_y: 70.0,
	atk_power: 1.2,
	cd: 0.0,
};

configdb.skill['10104'] = {
	key: 10104.0,
	name: undefined,
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 13.0,
	quake_time: 0.09,
	pause_time: 0.0,
	movement: 10.0,
	velocity_ground_x: 200.0,
	velocity_ground_y: 100.0,
	velocity_floating_x: 300.0,
	velocity_floating_y: 100.0,
	atk_power: 1.3,
	cd: 0.0,
};

configdb.skill['10105'] = {
	key: 10105.0,
	name: undefined,
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 15.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 200.0,
	velocity_ground_x: 300.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 800.0,
	velocity_floating_y: 70.0,
	atk_power: 1.4,
	cd: 0.0,
};

configdb.skill['10106'] = {
	key: 10106.0,
	name: "审判之剑",
	icon: "images/icon/skill/skill1.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 1001.0,
	quake_intensity: 15.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 300.0,
	velocity_ground_x: 300.0,
	velocity_ground_y: 100.0,
	velocity_floating_x: 1500.0,
	velocity_floating_y: 50.0,
	atk_power: undefined,
	cd: 6.0,
};

configdb.skill['10107'] = {
	key: 10107.0,
	name: "幻影乱舞",
	icon: "images/icon/skill/skill4.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 2001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 8.0,
};

configdb.skill['10108'] = {
	key: 10108.0,
	name: "奇迹结界",
	icon: "images/icon/skill/skill2.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 3001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 10.0,
};

configdb.skill['10109'] = {
	key: 10109.0,
	name: "誓约胜利之剑",
	icon: "images/icon/skill/skill3.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 4001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 30.0,
};

configdb.skill['10110'] = {
	key: 10110.0,
	name: "冲刺",
	icon: "images/icon/skill/skill4.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['10201'] = {
	key: 10201.0,
	name: "幻界",
	icon: "images/icon/skill/skill1_1.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 1101.0,
	quake_intensity: 15.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 300.0,
	velocity_ground_x: 300.0,
	velocity_ground_y: 100.0,
	velocity_floating_x: 1500.0,
	velocity_floating_y: 50.0,
	atk_power: undefined,
	cd: 6.0,
};

configdb.skill['10202'] = {
	key: 10202.0,
	name: "百刃",
	icon: "images/icon/skill/skill4_1.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 2101.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 8.0,
};

configdb.skill['10203'] = {
	key: 10203.0,
	name: "碎星斩",
	icon: "images/icon/skill/skill2_1.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 3101.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 10.0,
};

configdb.skill['10204'] = {
	key: 10204.0,
	name: "伪·螺旋剑",
	icon: "images/icon/skill/skill3_1.png",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 4101.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 30.0,
};

configdb.skill['20001'] = {
	key: 20001.0,
	name: undefined,
	icon: undefined,
	strongStatus: 1.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 0.0,
	velocity_ground_x: 0.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 300.0,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['20002'] = {
	key: 20002.0,
	name: "caster全屏火球",
	icon: undefined,
	strongStatus: 0.0,
	throw_model_id: 1002.0,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 0.0,
	velocity_ground_x: 0.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 0.0,
	velocity_floating_y: 0.0,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['20003'] = {
	key: 20003.0,
	name: undefined,
	icon: undefined,
	strongStatus: 1.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.0,
	movement: 0.0,
	velocity_ground_x: 500.0,
	velocity_ground_y: 700.0,
	velocity_floating_x: 0.0,
	velocity_floating_y: 0.0,
	atk_power: undefined,
	cd: undefined,
};

