//Auto gen file

var configdb = configdb || {};

configdb.item = {};

configdb.item['100001'] = {
	key: 100001.0,
	name: "复活币",
	desc: "可以在战斗中复活的币",
	icon: undefined,
	type: 4.0,
	level: 1.0,
	req: 1.0,
	price: 123.0,
	stack : 9999.0,
	sort: 1.0,
	result: undefined,
	result_value: undefined,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100002'] = {
	key: 100002.0,
	name: "金币",
	desc: "有钱能使鬼推磨",
	icon: "images/icon/icon_02.png",
	type: 1.0,
	level: 1.0,
	req: 1.0,
	price: 0.0,
	stack : 99999.0,
	sort: 2.0,
	result: 2.0,
	result_value: 1.0,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100003'] = {
	key: 100003.0,
	name: "钻石",
	desc: "有钻也能使鬼推磨",
	icon: "images/icon/icon_03.png",
	type: 1.0,
	level: 1.0,
	req: 1.0,
	price: 0.0,
	stack : 99999.0,
	sort: 4.0,
	result: 3.0,
	result_value: 1.0,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100004'] = {
	key: 100004.0,
	name: "经验",
	desc: "没有经验你怎么毕业的！",
	icon: undefined,
	type: 6.0,
	level: 1.0,
	req: 1.0,
	price: 0.0,
	stack : 99999.0,
	sort: 3.0,
	result: 1.0,
	result_value: 1.0,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100005'] = {
	key: 100005.0,
	name: "血瓶",
	desc: "喝了后感觉自己更有干净了",
	icon: undefined,
	type: 4.0,
	level: 1.0,
	req: 1.0,
	price: 0.0,
	stack : 99999.0,
	sort: undefined,
	result: 5.0,
	result_value: 0.6,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100006'] = {
	key: 100006.0,
	name: "蓝瓶",
	desc: "要让自己萌哒哒，就靠这蓝瓶",
	icon: undefined,
	type: 4.0,
	level: 1.0,
	req: 1.0,
	price: 0.0,
	stack : 99999.0,
	sort: undefined,
	result: 6.0,
	result_value: 0.6,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100007'] = {
	key: 100007.0,
	name: "10次经验书",
	desc: undefined,
	icon: undefined,
	type: undefined,
	level: undefined,
	req: undefined,
	price: undefined,
	stack : undefined,
	sort: undefined,
	result: undefined,
	result_value: undefined,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

configdb.item['100008'] = {
	key: 100008.0,
	name: "20倍经验书",
	desc: undefined,
	icon: undefined,
	type: undefined,
	level: undefined,
	req: undefined,
	price: undefined,
	stack : undefined,
	sort: undefined,
	result: undefined,
	result_value: undefined,
	gift1: undefined,
	gift1_val: undefined,
	gift2: undefined,
	gift2_val: undefined,
	gift3: undefined,
	gift3_val: undefined,
	gift4: undefined,
	gift4_val: undefined,
	gift5: undefined,
	gift5_val: undefined,
};

