//Auto gen file

var configdb = configdb || {};

configdb.skill = {};

configdb.skill['10101'] = {
	key: 10101.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.06,
	movement: 10.0,
	velocity_ground_x: 180.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 300.0,
	atk_power: 1.0,
	cd: 0.0,
};

configdb.skill['10102'] = {
	key: 10102.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.06,
	movement: 10.0,
	velocity_ground_x: 180.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 300.0,
	atk_power: 1.1,
	cd: 0.0,
};

configdb.skill['10103'] = {
	key: 10103.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 8.0,
	quake_time: 0.05,
	pause_time: 0.06,
	movement: 150.0,
	velocity_ground_x: 200.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 200.0,
	velocity_floating_y: 300.0,
	atk_power: 1.2,
	cd: 0.0,
};

configdb.skill['10104'] = {
	key: 10104.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 13.0,
	quake_time: 0.09,
	pause_time: 0.1,
	movement: 10.0,
	velocity_ground_x: 200.0,
	velocity_ground_y: 780.0,
	velocity_floating_x: 200.0,
	velocity_floating_y: 400.0,
	atk_power: 1.3,
	cd: 0.0,
};

configdb.skill['10105'] = {
	key: 10105.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 15.0,
	quake_time: 0.05,
	pause_time: 0.15,
	movement: 200.0,
	velocity_ground_x: 300.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 400.0,
	velocity_floating_y: 250.0,
	atk_power: 1.4,
	cd: 0.0,
};

configdb.skill['10106'] = {
	key: 10106.0,
	name: "审判之剑",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 1001.0,
	quake_intensity: 15.0,
	quake_time: 0.05,
	pause_time: 0.05,
	movement: 300.0,
	velocity_ground_x: 300.0,
	velocity_ground_y: 780.0,
	velocity_floating_x: 800.0,
	velocity_floating_y: 250.0,
	atk_power: 1.5,
	cd: 4.0,
};

configdb.skill['10107'] = {
	key: 10107.0,
	name: "幻影乱舞",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 2001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 6.0,
};

configdb.skill['10108'] = {
	key: 10108.0,
	name: "奇迹结界",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 3001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 8.0,
};

configdb.skill['10109'] = {
	key: 10109.0,
	name: "誓约胜利之剑",
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: 4001.0,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: 30.0,
};

configdb.skill['10110'] = {
	key: 10110.0,
	name: undefined,
	strongStatus: 0.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: undefined,
	quake_time: undefined,
	pause_time: undefined,
	movement: undefined,
	velocity_ground_x: undefined,
	velocity_ground_y: undefined,
	velocity_floating_x: undefined,
	velocity_floating_y: undefined,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['20001'] = {
	key: 20001.0,
	name: undefined,
	strongStatus: 1.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.05,
	movement: 0.0,
	velocity_ground_x: 0.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 90.0,
	velocity_floating_y: 300.0,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['20002'] = {
	key: 20002.0,
	name: "caster全屏火球",
	strongStatus: 0.0,
	throw_model_id: 1002.0,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.05,
	movement: 0.0,
	velocity_ground_x: 0.0,
	velocity_ground_y: 0.0,
	velocity_floating_x: 0.0,
	velocity_floating_y: 0.0,
	atk_power: undefined,
	cd: undefined,
};

configdb.skill['20003'] = {
	key: 20003.0,
	name: undefined,
	strongStatus: 1.0,
	throw_model_id: undefined,
	skillup_id: undefined,
	quake_intensity: 5.0,
	quake_time: 0.05,
	pause_time: 0.05,
	movement: 0.0,
	velocity_ground_x: 500.0,
	velocity_ground_y: 700.0,
	velocity_floating_x: 0.0,
	velocity_floating_y: 0.0,
	atk_power: undefined,
	cd: undefined,
};

